### ISSUE TITLE
Problems hdf5_getters

### ISSUE THREAD

**Issue by elisevmol** [elisevmol/MRWP-Project#3]
Hey martine, I cant seem to import hdf5_getters, and in the tutorial it doesn't seem to explain further. Error 

```
----> 9 import hdf5_getters

ImportError: No module named hdf5_getters
```

Do you know how you fixed that? And whether or not I am just missing a step in my code?

**Comment by Mkeulen** [comment]
You need to run that line, after you've defined the paths to your code. Does that help?

**Comment by elisevmol** [comment]
Was solved by changing brackets from \ to /
